apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-repay-bot
  namespace: prod
  labels:
    env: prod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: auto-repay-bot
  template:
    metadata:
      name: auto-repay-bot
      labels:
        env: prod
        app: auto-repay-bot
    spec:
      containers:
        - image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          name: app
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: festive-cirrus-452916-c1
            - name: RPC_URLS
              valueFrom:
                secretKeyRef:
                  name: rpc-urls
                  key: key
            - name: LIQUIDATOR_KEYPAIR
              valueFrom:
                secretKeyRef:
                  name: liquidator-keypair
                  key: key
            - name: EMAIL_TO
              value: iarla@pyra.fi,diego@pyra.fi
            - name: EMAIL_FROM
              value: diego@pyra.fi
            - name: EMAIL_HOST
              value: smtp-relay.brevo.com
            - name: EMAIL_PORT
              value: "587"
            - name: EMAIL_USER
              value: 77aaea001@smtp-brevo.com
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-password
                  key: key
            - name: INTERNAL_API_URL
              value: https://api.pyra.fi/card/
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 1500m
          securityContext:
            runAsUser: 1005
            runAsNonRoot: true
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: auto-repay-bot
  namespace: prod
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auto-repay-bot
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: app
        minAllowed:
          cpu: 100m
          memory: 128Mi
        maxAllowed:
          cpu: 1500m
          memory: 2Gi
        controlledResources: ["cpu", "memory"]
